### ISSUE TITLE
Dotdrop issue

### ISSUE THREAD

**Issue by akashgagda** [ask1234560/dotfiles_bspwm#1]
I enter same command when i hit final command ./dotdrop.sh install
It's show [WARN] no dotfile to install for this profile ("Matrix")

**Comment by ask1234560** [comment]
You have to edit config.yaml

```
profiles:
  arch:
    dotfiles:
    - f_zshrc
    - f_bashrc

```

Here arch is the hostname, change it to 'Matrix' and add or remove the entries you want like zshrc or bashrc.

Here config.yaml contains user specific configs and global-config.yaml contains system wide configs.
